#!/usr/bin/env python3
"""Generate RSA-2048 key pair for offline license signing (run once on your machine)."""

from __future__ import annotations

import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

KEYGEN_DIR = Path(__file__).resolve().parent
ROOT = KEYGEN_DIR.parent
EMBED_PATH = ROOT / "licensing" / "public_key_embed.py"


def main() -> None:
    private_path = KEYGEN_DIR / "private_key.pem"
    public_path = KEYGEN_DIR / "public_key.pem"

    if private_path.exists():
        print(f"[WARN] {private_path} already exists — refusing to overwrite.")
        print("Delete it first if you really want new keys.")
        sys.exit(1)

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_bytes = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    private_path.write_bytes(private_bytes)
    public_path.write_bytes(public_bytes)

    pem_text = public_bytes.decode("utf-8")
    EMBED_PATH.write_text(
        '"""AUTO-GENERATED by keygen/generate_keys.py — do not edit."""\n\n'
        f'PUBLIC_KEY_PEM = """{pem_text}"""\n',
        encoding="utf-8",
    )

    print(f"[OK] Private key: {private_path}")
    print(f"[OK] Public key:  {public_path}")
    print(f"[OK] Embedded for exe: {EMBED_PATH}")
    print("\nKeep private_key.pem secret. Never bundle it into the customer .exe.")
    print("Rebuild portable exes after embedding the public key.")


if __name__ == "__main__":
    main()
